<?php
/**
 * This configuration cache file was generated by Zend\ConfigAggregator\ConfigAggregator
 * at 2019-11-23T15:15:44+01:00
 */
return array (
  'dependencies' => 
  array (
    'aliases' => 
    array (
      'Zend\\Expressive\\Template\\TemplateRendererInterface' => 'Zend\\Expressive\\ZendView\\ZendViewRenderer',
      'Zend\\Expressive\\Router\\RouterInterface' => 'Zend\\Expressive\\Router\\ZendRouter',
      'HttpRouter' => 'Zend\\Router\\Http\\TreeRouteStack',
      'router' => 'Zend\\Router\\RouteStackInterface',
      'Router' => 'Zend\\Router\\RouteStackInterface',
      'RoutePluginManager' => 'Zend\\Router\\RoutePluginManager',
      'ValidatorManager' => 'Zend\\Validator\\ValidatorPluginManager',
      'Zend\\Expressive\\Delegate\\DefaultDelegate' => 'Zend\\Expressive\\Handler\\NotFoundHandler',
      'Zend\\Expressive\\Middleware\\DispatchMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\DispatchMiddleware',
      'Zend\\Expressive\\Middleware\\ImplicitHeadMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\ImplicitHeadMiddleware',
      'Zend\\Expressive\\Middleware\\ImplicitOptionsMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\ImplicitOptionsMiddleware',
      'Zend\\Expressive\\Middleware\\NotFoundMiddleware' => 'Zend\\Expressive\\Handler\\NotFoundHandler',
      'Zend\\Expressive\\Middleware\\RouteMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\RouteMiddleware',
    ),
    'factories' => 
    array (
      'Zend\\View\\HelperPluginManager' => 'Zend\\Expressive\\ZendView\\HelperPluginManagerFactory',
      'Zend\\Expressive\\ZendView\\ZendViewRenderer' => 'Zend\\Expressive\\ZendView\\ZendViewRendererFactory',
      'Zend\\Router\\Http\\TreeRouteStack' => 'Zend\\Router\\Http\\HttpRouterFactory',
      'Zend\\Router\\RoutePluginManager' => 'Zend\\Router\\RoutePluginManagerFactory',
      'Zend\\Router\\RouteStackInterface' => 'Zend\\Router\\RouterFactory',
      'Zend\\Validator\\ValidatorPluginManager' => 'Zend\\Validator\\ValidatorPluginManagerFactory',
      'Zend\\Expressive\\Helper\\ServerUrlMiddleware' => 'Zend\\Expressive\\Helper\\ServerUrlMiddlewareFactory',
      'Zend\\Expressive\\Helper\\UrlHelper' => 'Zend\\Expressive\\Helper\\UrlHelperFactory',
      'Zend\\Expressive\\Helper\\UrlHelperMiddleware' => 'Zend\\Expressive\\Helper\\UrlHelperMiddlewareFactory',
      'Zend\\Expressive\\Application' => 'Zend\\Expressive\\Container\\ApplicationFactory',
      'Zend\\Expressive\\ApplicationPipeline' => 'Zend\\Expressive\\Container\\ApplicationPipelineFactory',
      'Zend\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Zend\\Expressive\\Container\\EmitterFactory',
      'Zend\\Stratigility\\Middleware\\ErrorHandler' => 'Zend\\Expressive\\Container\\ErrorHandlerFactory',
      'Zend\\Expressive\\Handler\\NotFoundHandler' => 'Zend\\Expressive\\Container\\NotFoundHandlerFactory',
      'Zend\\Expressive\\MiddlewareContainer' => 'Zend\\Expressive\\Container\\MiddlewareContainerFactory',
      'Zend\\Expressive\\MiddlewareFactory' => 'Zend\\Expressive\\Container\\MiddlewareFactoryFactory',
      'Zend\\Expressive\\Middleware\\ErrorResponseGenerator' => 'Zend\\Expressive\\Container\\ErrorResponseGeneratorFactory',
      'Zend\\HttpHandlerRunner\\RequestHandlerRunner' => 'Zend\\Expressive\\Container\\RequestHandlerRunnerFactory',
      'Psr\\Http\\Message\\ResponseInterface' => 'Zend\\Expressive\\Container\\ResponseFactoryFactory',
      'Zend\\Expressive\\Response\\ServerRequestErrorResponseGenerator' => 'Zend\\Expressive\\Container\\ServerRequestErrorResponseGeneratorFactory',
      'Psr\\Http\\Message\\ServerRequestInterface' => 'Zend\\Expressive\\Container\\ServerRequestFactoryFactory',
      'Psr\\Http\\Message\\StreamInterface' => 'Zend\\Expressive\\Container\\StreamFactoryFactory',
      'Zend\\Expressive\\Router\\Middleware\\DispatchMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\DispatchMiddlewareFactory',
      'Zend\\Expressive\\Router\\Middleware\\ImplicitHeadMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\ImplicitHeadMiddlewareFactory',
      'Zend\\Expressive\\Router\\Middleware\\ImplicitOptionsMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\ImplicitOptionsMiddlewareFactory',
      'Zend\\Expressive\\Router\\Middleware\\MethodNotAllowedMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\MethodNotAllowedMiddlewareFactory',
      'Zend\\Expressive\\Router\\Middleware\\RouteMiddleware' => 'Zend\\Expressive\\Router\\Middleware\\RouteMiddlewareFactory',
      'Zend\\Expressive\\Router\\RouteCollector' => 'Zend\\Expressive\\Router\\RouteCollectorFactory',
      'App\\Handler\\HomePageHandler' => 'App\\Handler\\HomePageHandlerFactory',
    ),
    'invokables' => 
    array (
      'Zend\\Expressive\\Router\\ZendRouter' => 'Zend\\Expressive\\Router\\ZendRouter',
      'Zend\\Expressive\\Helper\\ServerUrlHelper' => 'Zend\\Expressive\\Helper\\ServerUrlHelper',
      'Zend\\Expressive\\Helper\\Template\\TemplateVariableContainerMiddleware' => 'Zend\\Expressive\\Helper\\Template\\TemplateVariableContainerMiddleware',
      'App\\Handler\\PingHandler' => 'App\\Handler\\PingHandler',
    ),
  ),
  'templates' => 
  array (
    'extension' => 'phtml',
    'layout' => 'layout::default',
    'paths' => 
    array (
      'app' => 
      array (
        0 => '/var/www/html/src/App/src/../templates/app',
      ),
      'error' => 
      array (
        0 => '/var/www/html/src/App/src/../templates/error',
      ),
      'layout' => 
      array (
        0 => '/var/www/html/src/App/src/../templates/layout',
      ),
    ),
  ),
  'route_manager' => 
  array (
  ),
  'config_cache_path' => 'data/cache/config-cache.php',
  'config_cache_enabled' => true,
  'debug' => false,
  'zend-expressive' => 
  array (
    'error_handler' => 
    array (
      'template_404' => 'error::404',
      'template_error' => 'error::error',
    ),
  ),
);
